version: "3.7"

services:
  db:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    env_file: ./.env #Here we are using the already existing .env.local file
    ports:
      - "5432:5432"

  db-test:
    image: postgres:latest
    env_file: ./.env.test.local
    ports:
      - 5433:5432

  app:
    image: mpppk/tatoe
    env_file: ./.env.docker.local
    ports:
      - 3000:3000

volumes:
  data:
